package com.cg.vms.service;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.apache.logging.log4j.LogManager;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.cg.vms.entities.Booking;
import com.cg.vms.entities.Payment;
import com.cg.vms.entities.Vehicle;
import com.cg.vms.repository.IBookingRepository;
import com.cg.vms.repository.IPaymentRepository;

@Service
public class PaymentServiceImp implements IPaymentService {

	@Autowired
	IPaymentRepository payRepo;
	
	/**
	 * Logger - Payment
	 */
	org.apache.logging.log4j.Logger logger = LogManager.getLogger(PaymentServiceImp.class);

	@Autowired
	IBookingRepository bokRepo;
	
	/**
	 * Logger - Booking
	 */
	org.apache.logging.log4j.Logger logger1 = LogManager.getLogger(BookingServiceImpl.class);

	/**
	 * Used to store the payment details passed from the controller
	 * 
	 * @return
	 */
	@Override
	public Payment addPayment(Payment payment) {
		logger.info("Adding the payment details to the database");
		return payRepo.save(payment);
	}

	/**
	 * used to Cancel a payment by paymentId
	 * 
	 * @return
	 */
	@Override
	public Payment cancelPayment(int p) {
		logger.info("Deleting the payment detail by paymentId");
		Optional<Payment> pa = payRepo.findById(p);
		if (!pa.isPresent()) {
			return null;
		}
		payRepo.deleteById(p);
		return pa.get();
	}

	/**
	 * Get a payment by paymentId
	 */
	@Override
	public Payment viewPayment(int b) {
		logger.info("View a payment detail by paymentId");
		Optional<Payment> pa = payRepo.findById(b);
		if (!pa.isPresent()) {
			return null;
		}
		return pa.get();
	}

	/**
	 * Get all the payments by vehicle
	 * 
	 * @return
	 */
	@Override
	public List<Payment> viewAllPayments(Vehicle vehicle) {
		logger.info("Viewing all the payments from the database by vehicle");
		return payRepo.findAll();
	}

	/**
	 * Get all the payments
	 */
	@Override
	public List<Payment> viewAllPayments() {
		logger.info("Viewing all the payments from the database");
		return payRepo.findAll();
	}

	/**
	 * This function will update the payment details
	 */
	@Override
	public Payment updatePaymentStatus(int paymentId, Payment payment) {
		logger.info("Updating a payment status using paymentId and payment");
		Optional<Payment> pa = payRepo.findById(paymentId);
		if (pa.isPresent()) {
			pa.get().setPaymentStatus(payment.getPaymentStatus());
			return payRepo.save(pa.get());
		}
		return null;
	}

	/**
	 * This function will calculate the monthly revenue generated within a date range such as bookingStartDate and bookingEndDate
	 */
	@Override
	public double calculateMonthlyRevenue(LocalDate d1, LocalDate d2) {
		logger.info("Calculating the monthly revenue generated by giving bookingStartDate d1 and bookingEndDat d2");
		return payRepo.calculateMonthlyRevenue(d1, d2);
	}

	/**
	 * This function will calculate the total payment generated within a booking id range such as bookingStartId and bookingEndId
	 */
	@Override
	public double calculateTotalPayment(int bookingStartId, int bookingEndId) {
		logger.info("Calculating the total payment generated by giving bookingStartId and bookingEndId");
		return payRepo.calculateTotalPayment(bookingStartId, bookingEndId);
	}

	/**
	 * This function will calculate the total booking cost using paymentId, booking distance and vehicle
	 */
	@Override
	public Booking calculateTotalBookingCost(int paymentId, double distance, Vehicle vehicle) {
		logger1.info("Calculating the total booking cost generated by giving paymentId, booking distance, vehicle");
		Optional<Payment> opt = payRepo.findById(paymentId);
		if (opt.isPresent()) {

			Payment payment = opt.get();
			Booking booking = payment.getBooking();
			booking.setDistance(distance);
			bokRepo.save(booking);
		}
		Optional<Payment> opt1 = payRepo.findById(paymentId);
		if (!opt1.isPresent()) {
			return null;
		}
		Payment payment2 = opt1.get();
		Booking booking1 = payment2.getBooking();
		booking1.setDistance(distance);
		double totalCost = (vehicle.getChargesPerKM() * distance) + vehicle.getFixedCharges();
		booking1.setTotalCost(totalCost);
		return bokRepo.save(booking1);
	}

}
